catalyst/moodle-MDL-70329

- mod/qbank/classes/privacy/provider.php
> Issue #19: Add null provider.

- mod/qbank/lib.php
- mod/qbank/mod_form.php
- mod/qbank/view.php
> Master mdl 71378

- mod/qbank/lang/en/qbank.php
I think this would be the time to already add modulename_help since it is visible if you click (i) in the activity chooser.
> modulename_help

- lib/classes/plugin_manager.php
- question/bank/viewcheckbox/classes/viewcheckbox_column.php
- question/bank/viewcheckbox/lang/en/qbank_viewcheckbox.php
- question/bank/viewcheckbox/version.php
> viewcheckbox plugin build

- lib/classes/plugin_manager.php
- question/bank/viewquestiontext/classes/viewquestiontext_column.php
- question/bank/viewquestiontext/lang/en/qbank_viewquestiontext.php
- question/bank/viewquestiontext/version.php
> viewquestiontext plugin build

- question/tests/bank_view_test.php
> Fix unit test Issue 94

- lib/classes/plugin_manager.php
- question/bank/viewcheckbox/classes/privacy/provider.php
- question/bank/viewcheckbox/classes/viewcheckbox_column.php
- question/bank/viewcheckbox/lang/en/qbank_viewcheckbox.php
- question/bank/viewcheckbox/version.php
> Master mdl 71579 60

- mod/qbank/classes/helper.php
- mod/qbank/db/install.php
- mod/qbank/tests/coursecreation_test.php
Assertions and helper class + methods for get_populated and course_exists
> Add helper class and unit tests

- admin/tool/lp/lib.php
- course/moodleform_mod.php
- lib/moodlelib.php
Add missing features that can be controlled when adding a new module to core.
> Add new features to moodleform_mod

- mod/qbank/classes/helper.php
- mod/qbank/db/install.php
- mod/qbank/lang/en/qbank.php
- mod/qbank/tests/coursecreation_test.php
PR for Issue #90 : Helper class with methods : get_populated and course_exists + unit tests
> Master mdl 71378 90

- course/tests/fixtures/mod_form.php
- course/tests/moodleform_mod_test.php
Unit test to control features.
> Add unit tests (Issue 25)

- mod/qbank/classes/helper.php
- mod/qbank/db/install.php
- mod/qbank/tests/coursecreation_test.php
- mod/qbank/tests/qbankcreation_test.php
Added cases for :
- CONTEXT_SYSTEM
- CONTEXT_COURSE
- CONTEXT_MODULE
Altered CONTEXT_COURSECAT in case course already exists.
Added method:
- create_qbank_instance
- get_coursecatid
- get_coursemoduleid
- get_qbank
Altered sql query in method get_categories_populated to get question category name and ids.
Added one unit test for create_qbank_instance in tests/qbankcreation_test.php
--
> Master mdl 71378 91 dev

- lib/questionlib.php
- question/classes/local/bank/navigation_plugin_base.php
PR for autoloading navigation - i had a crazy idea, implement it and worked!
> autoload navigation from plugins

- lib/classes/plugin_manager.php
- question/bank/viewquestiontype/classes/columns.php
- question/bank/viewquestiontype/classes/privacy/provider.php
- question/bank/viewquestiontype/classes/question_type_column.php
- question/bank/viewquestiontype/lang/en/qbank_viewquestiontype.php
- question/bank/viewquestiontype/version.php
- question/classes/bank/question_type_column.php
> Master mdl 71577 64

- mod/qbank/db/access.php
- mod/qbank/lang/en/qbank.php
- mod/qbank/version.php
Add new capability qbank:viewhidden
> Add qbank:viewhidden capability

- lib/classes/plugin_manager.php
- question/bank/viewquestiontext/classes/columns.php
- question/bank/viewquestiontext/classes/privacy/provider.php
- question/bank/viewquestiontext/classes/question_text_row.php
- question/bank/viewquestiontext/lang/en/qbank_viewquestiontext.php
- question/bank/viewquestiontext/version.php
> Master mdl 71575 68

- question/classes/local/bank/helper.php
> helper class

- lib/questionlib.php
- question/classes/local/bank/navigation_plugin_base.php
> additional capability feature for navigation node plugins

- lib/classes/plugin_manager.php
- lib/questionlib.php
- question/bank/exportquestions/classes/exportquestions_helper.php
- question/bank/exportquestions/classes/form/export_form.php
- question/bank/exportquestions/classes/navigation.php
- question/bank/exportquestions/classes/privacy/provider.php
- question/bank/exportquestions/export.php
- question/bank/exportquestions/lang/en/qbank_exportquestions.php
- question/bank/exportquestions/version.php
- question/format.php
> Master mdl 71573 57

- lib/classes/plugin_manager.php
- lib/questionlib.php
- lib/tests/questionlib_test.php
- question/bank/exporttoxml/classes/columns.php
- question/bank/exporttoxml/classes/export_xml_action_column.php
- question/bank/exporttoxml/classes/exporttoxml_helper.php
- question/bank/exporttoxml/classes/privacy/provider.php
- question/bank/exporttoxml/exportone.php
- question/bank/exporttoxml/lang/en/qbank_exporttoxml.php
- question/bank/exporttoxml/tests/qbank_exporttoxml_test.php
- question/bank/exporttoxml/version.php
> Master mdl 71639 85

- lib/classes/plugin_manager.php
- question/bank/deletequestion/classes/columns.php
- question/bank/deletequestion/classes/delete_action_column.php
- question/bank/deletequestion/classes/privacy/provider.php
- question/bank/deletequestion/delete.php
- question/bank/deletequestion/lang/en/qbank_deletequestion.php
- question/bank/deletequestion/version.php
> Master mdl 71615 82

- mod/qbank/classes/helper.php
- mod/qbank/db/install.php
- mod/qbank/lang/en/qbank.php
hi @mattporritt @safatshahin can you have a look to this PR please:
1. Create mod_qbank in section 0.
2. Data for course name and mod_qbank instance name passed as lang string variables.
3. Make a mod_qbank description based on a lang string that explains why the mod was created.
> fix name when create courses and activities

- lib/classes/plugin_manager.php
- question/bank/importquestions/classes/form/import_form.php
- question/bank/importquestions/classes/navigation.php
- question/bank/importquestions/classes/privacy/provider.php
- question/bank/importquestions/import.php
- question/bank/importquestions/lang/en/qbank_importquestions.php
- question/bank/importquestions/version.php
PR for issue https://github.com/catalyst/moodle-MDL-70329/issues/56:
- question/bank/importquestions/classes/form/import_form.php
- question/bank/importquestions/classes/navigation.php
- question/bank/importquestions/classes/privacy/provider.php
- question/bank/importquestions/import.php
- question/bank/importquestions/lang/en/qbank_importquestions.php
- question/bank/importquestions/version.php
- lib/classes/plugin_manager.php
Code checker run : ok
core_question_testsuite: ok
> master_MDL-71608-56 importquestions

- mod/qbank/classes/event/course_module_instance_list_viewed.php
- mod/qbank/index.php
- mod/qbank/lang/en/qbank.php
This PR is created It is created to fix and display the index page correctly in mod_qbank.
> Fix index page mod_qbank

- lib/navigationlib.php
- lib/questionlib.php
Hi @safatshahin 
This PR changes the nodes added to the navigation in course/admin.php for Question Banks.
Thank you.
> Replace node navigation in navigationlib.php

- lib/form/questioncategory.php
- lib/questionlib.php
- question/bank/managecategories/classes/helper.php
- question/bank/managecategories/classes/question_category_list.php
- question/classes/bank/search/category_condition.php
- question/classes/local/bank/view.php
> Refactor questionlib.php into managecategories_helper

- lang/en/question.php
> String fix, should say 'question bank plugin'.

- lib/questionlib.php
- mod/qbank/lib.php
> Add module settings to navigation

- question/classes/external.php
- question/sortcolumns.php
- question/tests/columnsortorder_test.php
- question/tests/qbank_columnsortorder_test.php
This PR adds unit tests for columsortorder feature
- test_getcolumn_function
- test_columnorder_external
- test_view_ordering
> unit tests for qbank-columnsortorder

- backup/moodle2/restore_stepslib.php
- course/classes/category.php
- course/classes/deletecategory_form.php
- lang/en/deprecated.txt
- lang/en/moodle.php
- lang/en/question.php
- lib/moodlelib.php
- lib/questionlib.php
- lib/tests/questionlib_test.php
- lib/upgrade.txt
- question/tests/category_class_test.php
- question/tests/question_categories_test.php
> Create default question categories only for current context

- question/tests/behat/columnsortorder.feature
> mdl 71636 behat columnsortorder

- admin/qbankplugins.php
- lib/classes/plugininfo/qbank.php
Hi @safatshahin,
Here is the fix for the unremoved columns from db.
2 files were changed:
`admin/qbankplugins.php`
`lib/classes/plugininfo/qbank.php `
> JSON db fix disable/remove 71636 columnsortorder

- lib/questionlib.php
- question/bank/deletequestion/classes/delete_action_column.php
- question/bank/deletequestion/delete.php
- question/bank/editquestion/classes/editquestion_helper.php
- question/bank/editquestion/classes/output/renderer.php
- question/bank/editquestion/classes/question_status_column.php
- question/bank/editquestion/lang/en/qbank_editquestion.php
- question/bank/editquestion/question.php
- question/bank/editquestion/templates/question_info.mustache
- question/bank/viewcreator/classes/output/renderer.php
- question/bank/viewcreator/lang/en/qbank_viewcreator.php
- question/bank/viewcreator/lib.php
- question/bank/viewcreator/templates/version_info.mustache
- question/classes/bank/search/hidden_condition.php
- question/classes/local/bank/action_column_base.php
- question/classes/local/bank/constants.php
- question/classes/local/bank/view.php
- question/type/edit_question_form.php
PR for question status and question base view.
> MDL-71696 core_question: changes for question status and view

- report/questioninstances/index.php
PR for question instance report
> Master mdl 71696 versioning questioninstance report

- lib/db/install.xml
- lib/db/upgrade.php
- lib/db/upgradelib.php
Remove fields from question table.
> Remove question fields

- question/bank/viewcreator/tests/behat/view_view_creator_column.feature
Behat test for viewcreator plugin
> behat test MDL 71613 viewcreator

- mod/quiz/classes/local/structure/slot_random.php
- mod/quiz/locallib.php
- mod/quiz/tests/local_structure_slot_random_test.php
- question/bank/managecategories/tests/helper_test.php
- question/type/questiontypebase.php
mod_quiz_local_structure_slot_random_test  fixed
> Fix unit tests

- question/type/match/tests/questiontype_test.php
- question/type/multichoice/tests/questiontype_test.php
- question/type/numerical/tests/questiontype_test.php
- question/type/shortanswer/tests/questiontype_test.php
- question/type/truefalse/tests/questiontype_test.php
- Fix idnumber missing in query unit tests
-
> Fix idnumber missing in query unit tests

- question/bank/tagquestion/classes/tag_condition.php
Hi @safatshahin, this is the PR for https://github.com/catalyst/moodle-MDL-70329/issues/373,
Thank you
> mdl 72321 `any` condition 373 

- question/bank/managecategories/tests/behat/behat_qbank_managecategories.php
- question/bank/managecategories/tests/behat/question_category_filtering.feature
Hi @safatshahin, here are the changes for #444,
it should be merged after #432, #49, #51, #381 and #384.
Cheers,
> Master mdl 72321 api changes 385 category

- question/bank/tagquestion/tests/behat/behat_qbank_tagquestion.php
- question/bank/tagquestion/tests/behat/question_tag_filtering.feature
Hi @safatshahin, here are the changes for #446,
it should be merged after #432, #49, #51, #381 and #384.
Cheers,
> Master mdl 72321 api changes 385 tag

- question/bank/statistics/tests/behat/behat_qbank_statistics.php
- question/bank/statistics/tests/behat/question_discrimination_filtering.feature
Hi @safatshahin, here are the changes for #445,
it should be merged after #432, #49, #51, #381 and #384.
Cheers,
> Master mdl 72321 api changes 385 discrimination

- question/bank/customfields/tests/behat/customfield_question.feature
- question/tests/behat/duplicate_questions.feature
- question/tests/behat/question_categories.feature
Hi @safatshahin, I made fixes for tag `@core_question`, there are two commits Issue 413 with fixes concerning question filtering, and another commit concerning specifically `customfield_question`,
Cheers,
> Master mdl 72321 api changes 413

- mod/quiz/report/overview/tests/behat/regrading.feature
Hi @safatshahin,
Here are behats for Issue #462
Cheers
> Issue 462 : Behat coverage for question versioning regrade

- question/bank/history/classes/question_history_view.php
- question/bank/history/history.php
- question/bank/history/tests/question_history_view_test.php
Hi @safatshahin,
This is a fix for qbank history unit test
Cheers
> Unit test fix for qbank history
